# Generated by Django 5.1.1 on 2024-11-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="desc",
            new_name="description",
        ),
    ]
