# Generated by Django 5.1.1 on 2024-11-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_rename_desc_news_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="external_link",
            field=models.URLField(),
        ),
    ]
